name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read      

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      - run: terraform validate
      - name: terraform plan
<<<<<<< HEAD
        run: terraform plan -var-file=terraform.tfvars -input=false -out=tfplan
=======
        run: terraform plan -input=false -var-file=terraform.tfvars -out=tfplan
>>>>>>> 417bfa70a897d48ab8872c3600cbdd1f46a55306
      - name: Show Terraform Plan
        run: terraform show tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  terraform-apply:

    needs: terraform-plan

    runs-on: ubuntu-latest

    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform
      - run: terraform init
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
