name: Terraform Destroy

on:

  workflow_dispatch:

jobs:

  destroy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -input=false -var-file=terraform.tfvars -auto-approve